version: '3'
services:
  todotests:
    image: mjgargani/puppeteer:trybe1.0
    depends_on:
      - todofrontend
      - todobackend
    environment:
      FRONT_HOST: todofrontend
  todofrontend:
    image: node:14-alpine
    ports:
      - "3000:3000"
    depends_on:
      - todobackend
    environment:
      REACT_APP_API_HOST: todobackend
  todobackend:
    image: node:14-alpine
    ports:
      - "3001:3001"
